kmeanspp:
	gcc -Wall -O2 -std=c11 -D_DEFAULT_SOURCE main.c kmeans.c -lm -o kmeanspp

debug:
	gcc -Wall -ggdb -std=c11 -D_DEFAULT_SOURCE main.c kmeans.c -lm -o kmeanspp

clean:
	rm -f kmeanspp *.csv *.svg
